In [ ]:
#%%
import yfinance as yf
import pandas as pd
import argparse
from datetime import datetime, timedelta
import os

ticker = 'AAPL' 
timeframe='1d'
start_date=None
end_date=None
output_file=None

if start_date is None:
    start_date = (datetime.now() - timedelta(days=365)).strftime('%Y-%m-%d')
if end_date is None:
    end_date = datetime.now().strftime('%Y-%m-%d')
if output_file is None:
    output_file = os.path.join('data', f"{ticker}_data.csv")

# Create the data directory if it doesn't exist
os.makedirs('data', exist_ok=True)

print(f"Downloading {ticker} data with timeframe '{timeframe}' from {start_date} to {end_date}...")

data = yf.download(
    ticker,
    start=start_date,
    end=end_date,
    interval=timeframe
)

Downloading AAPL data with timeframe '1d' from 2024-03-12 to 2025-03-12...
YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2024-03-12  172.415863  173.212106  170.206295  172.336237   59825400
2024-03-13  170.325760  172.376076  169.957488  171.958052   52488700
2024-03-14  172.186951  173.490792  171.241418  172.097377   72913500
2024-03-15  171.808746  171.808746  169.489695  170.365564  121664700
2024-03-18  172.903580  176.874834  172.704523  174.744891   75604200
...                ...         ...         ...         ...        ...
2025-03-05  235.740005  236.550003  229.229996  235.419998   47227600
2025-03-06  235.330002  237.860001  233.160004  234.440002   45170400
2025-03-07  239.070007  241.369995  234.759995  235.110001   46273600
2025-03-10  227.479996  236.160004  224.220001  235.539993   72071200
2025-03-11  220.839996  225.839996  217.449997  223.809998   76087700

[250 rows x 5 columns]

In [ ]:
data.columns = [c[0].lower() for c in data.columns]
data = data['open','high','low','close','volume']
data

                 close        high         low        open     volume
Date
2024-03-12  172.415863  173.212106  170.206295  172.336237   59825400
2024-03-13  170.325760  172.376076  169.957488  171.958052   52488700
2024-03-14  172.186951  173.490792  171.241418  172.097377   72913500
2024-03-15  171.808746  171.808746  169.489695  170.365564  121664700
2024-03-18  172.903580  176.874834  172.704523  174.744891   75604200
...                ...         ...         ...         ...        ...
2025-03-05  235.740005  236.550003  229.229996  235.419998   47227600
2025-03-06  235.330002  237.860001  233.160004  234.440002   45170400
2025-03-07  239.070007  241.369995  234.759995  235.110001   46273600
2025-03-10  227.479996  236.160004  224.220001  235.539993   72071200
2025-03-11  220.839996  225.839996  217.449997  223.809998   76087700

[250 rows x 5 columns]